### ISSUE TITLE
UnsolvedError exception

### ISSUE THREAD

**Issue by paul-scott** [stanle/madopt#12]
I'm using bonmin through the python interface.  I have the situation where something is throwing a Bonmin::TNLPSolver::UnsolvedError when the solver reaches maximum time.  At other times it just returns the correct exit code so it is not consistent.

This exception is not caught in c++ and it ends up triggering a signal 6 which kills the python program.

First question is have you experienced this, and do you know when bonmin will throw such an exception?  If it is a recoverable situation perhaps we should just catch it in the madopt c++ and properly manage it.  It could be a bug in bonmin.

If you don't know anything about this then I'll investigate more and try to produce a repeatable example.

**Comment by paul-scott** [comment]
Reading a bit more it seems like this is likely thrown when either the filter, branching or ipopt solver fails to solve a (sub) problem.  In my case one thing I noticed is that the exception is thrown when the solver exits on maximum time without having found a feasible solution yet.  If it reaches maximum time and has found a feasible solution then all is ok and it returns the proper code without throwing.

It is probably correct behaviour of bonmin.  This is fine if you use the c++ interface to madopt because you can manage the exceptions manually, but when you are using the python interface it is not possible (so I believe).  I'm not familiar with cython, but perhaps there is a way to easily catch these exceptions and reraise python versions of them.  The other options is catch them in madopt and convert them to a return code or some form of status which can be accessed from python.

If you let me know what approach you prefer I can implement it, or feel free to do so yourself :).

**Comment by stanle** [comment]
I have created a solver status/ return code for it called UNSOLVED_ERROR. Let me know if that works for you. Catching the exception in cython will not be hard, but I have seen that Bonmin also catches the exception a couple of times in its code.

**Comment by paul-scott** [comment]
Yep this is a good solution for me, unfortunately I haven't been able to successfully test it yet.  I'm still getting uncaught exceptions but I'm pretty sure this must be something I'm doing wrong with the compilation where an old version of the library is still being used... I'll let you know when I've sorted it out.

**Comment by paul-scott** [comment]
OK so worked out the problem.  I know very little about exceptions in c++ but apparently you can either throw by value or a pointer (by value seems to be the common convention).  If you throw a value you can catch it by value or by reference, but if it is thrown as a pointer only catching it as a pointer will work.

Effectively it was passing through the catch you setup because a pointer is thrown...  I don't know if the source code ever also throws by value for the UnsolvedErrors, maybe it is safest to catch both by ref and pointer just in case.

If you do a fuzzy search for catch and UnsolvedError in the Bonmin src there are some examples of catching the error as a pointer.  They don't seem to be calling a delete on the pointer even though it appears that a new is called when creating it...  Not sure if this will leak memory... Maybe there is a simple way to test this?

**Comment by paul-scott** [comment]
If you don't notice see the above pull request for a working solution.
