### ISSUE TITLE
Any way to disable autodifferentiation?

### ISSUE THREAD

**Issue by scottpaine** [stanle/madopt#2]
I work with larger array sizes, but have pre-existing python code to perform quick gradient calculations even with these arrays.

I was wondering if it was possible to "turn off" the auto-differentiation if I include an objective function that can return both an objective value and the gradient values for variables at that point.

**Comment by stanle** [comment]
At the moment no.  If you do not need autodiff, you can use https://github.com/xuy/pyipopt.

**Comment by scottpaine** [comment]
Looking through that, I'm not immediately able to tell - does pyipopt support MINLP optimization? That was the biggest pull for me to your project

**Comment by stanle** [comment]
No it does not. It is an interface for Ipopt which is an NLP solver. The Mixed Interger extension of Ipopt is called Bonmin. 
I have an idea of how to add the feature you are looking for. Will take a couple of days.

**Comment by stanle** [comment]
Getting the callback working takes more worked than I expected. Also I am not sure how fast it will be given that we have to do a callback to python and might have to copy the data from the python object  to a c++ array which will slow things down. 
What is the problem with using the build in automatic differentiation? If there is some speed problem there, it might be easier to fix that.

**Comment by scottpaine** [comment]
It's a memory issue, currently.

When building the objective function, I have this (admittedly ugly) 5-dimensional array. This array is multiplied by constants (my optimization parameters), summed over one of the dimensions, squared, summed over ANOTHER dimension, and the remaining 3-dimensional array is used against a separate known 3-dimensional array in a sum of squared differences metric. I have memory-efficient methods for tracking all of this in python, and have my model set up to return an objective value and gradient terms for the active variables (of which there are only 18).

So the issue comes from keeping gradient and objective values in memory - even with a large amount of memory, I run out. 

It could just be an issue of too many possible permutations - I want those variables to be an integer between -5 and 5, so there are 18 variables which can be between those values which acts up memory saving nodes.

Sorry for rambling. The long and short of it is a memory issue with the objective/gradient functions.

**Comment by stanle** [comment]
When exactly do you run out of memory? Is it 
1) while constructing the expression for the objective
2) while calling model.setObj(expr)
3) after calling model.solve()

**Comment by stanle** [comment]
Let me elaborate a bit why I am asking, 

Once you have added all constraints and the objective and you are about to call model.solve(), madopt has reached its peak memory consumption. So if your memory consumption is high before you call solve(), the callback you want could potentially help avoiding the doubling information about the objective.

If on the other hand the total memory consumption is low before you call solve() and only later you ran out of memory then the problem is not within madopt but Bonmin. In this case there is nothing I can do for you. Might be compiling Bonmin with HSL support helps (if not done already), or there is some usefull option in Bonmin.

**Comment by scottpaine** [comment]
In my code, I run out of memory during construction of the expression for the objective. I never get to calling model.setObj.

**Comment by stanle** [comment]
Hey, I am looking into adding the feature you want, by my time is very limited at the moment, so It will not happen in the near future. Sorry.

**Comment by scottpaine** [comment]
Please, take all the time you need! I'm grateful that you're figuring it out and implementing it
