### ISSUE TITLE
Question about install madopt on mac

### ISSUE THREAD

**Issue by serenaTangarfff** [stanle/madopt#23]
hi,
I decide to install madpot for python on my MAC. I follow the install guideline, all the previous tasks are finished and without error, but when I running the last command"python setup.py install", the terminal shows error "command 'gcc' failed with exit status 1", here is the detailed information.

python setup.py install
running install
running build
running build_py
running build_ext
skipping 'src/madopt.cpp' Cython extension (up-to-date)
building 'madopt' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/madopt.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/madopt.o --std=c++11
src/madopt.cpp:10788:65: error: too many arguments to function call, expected 3,
      have 4
    return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~
/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h:100:18: note: 
      expanded from macro 'NULL'
#    define NULL __null
                 ^~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by ccoffrin** [comment]
I don't think this code is actively maintained.  You might give Python/Pyomo or Julia/JuMP a try.

**Comment by stanle** [comment]
True. but that does not automatically mean it doesn't work anymore. I do
not have a Mac, but I will have a look at the problem later in the week.

Also, if it is urgent,  Phono might do the trick as well.

**Comment by stanle** [comment]
what version of cyhton are you using?

**Comment by stanle** [comment]
https://github.com/numpy/numpy/issues/9391

this issue has the same error message due to and incompatibility between
cython and python 3.7
