### ISSUE TITLE
Model copy constructor dangerous

### ISSUE THREAD

**Issue by paul-scott** [stanle/madopt#9]
The Model class and subclasses do manual memory management.  The Model class still has its default copy and move constructors.  Should either "delete" these or implement them correctly.

**Comment by stanle** [comment]
I have deleted the Model copy and move constructors.

**Comment by paul-scott** [comment]
Supposedly the IpoptModel and BonminModel defaults still exist and should be deleted?  Also, I think the copy assignment and move assignment operators might need to be deleted.  Cannot remember the exact modern C++ guidelines on this right now.

If it is more convenient to actually allow copying/moving Models then using std::shared_ptr or std::unique_ptr instead of new might be more clean.  However, not sure whether or not this would work nicely with the internal smart pointers that IPOPT uses.

**Comment by stanle** [comment]
I have deleted the move&copy constructors for the IpoptModel and BonminModel. This seems to also have deleted the copy & move assignment operators.
Implementing them needs, as you say, a check if Ipopt does everything right. Gonna leave that for another time. So we should keep this issue open as a reminder.
